/**:
  ros__parameters:
    # Type:
    # Serial No.
    # Inspected Date:

    # Full Scale
    fs_list: [1000, 1000, 1000, 1000, 1000, 1000]

    # ITF
    itf_6axis_list: [1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                      0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
                      0.0, 0.0, 1.0, 0.0, 0.0, 0.0,
                      0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
                      0.0, 0.0, 0.0, 0.0, 1.0, 0.0,
                      0.0, 0.0, 0.0, 0.0, 0.0, 1.0]